print("#/============================/")
print("#/                            /")
print("#/       Program halo.py      /")
print("#/ by anton.s.p@mail.ugm.ac.id /")
print("#/                            /")
print("#/============================/")
